services:
  id-hash:
    pull_policy: never
    image: <your_built_image>
    ### EXAMPLE ###
    #image: ghcr.io/mygaru/id-hash:1.0.0
    container_name: id-hash
    restart: always
    # Use this if http proxy is the only way to contact the Internet (PKI/CA)
    environment:
      - https_proxy=http://10.210.210.1:3128/
      - http_proxy=http://10.210.210.1:3128/
      - no_proxy=localhost,127.0.0.1,10.210.129.0/24
    volumes:
      - ./configs/id-hash.ini:/etc/id-hash/base.ini
    ports:
      - "8000:8000"

