apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: id-hash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.adtelligent.com/myg/devops/myg-deployment.git
    targetRevision: master
    path: helm-charts

    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "deployment.server.image.tag"
        value: "TAG_NAME"
      valueFiles:
        - mygaru-values/ukrtelecom/values.gpsi.yaml
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: idr

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
