[http]
httpServerListenAddr        = :8000
httpServerName              = MyGaru ID HASH
# allow only ID CHECK to access!
httpAuthAllowedRemoteIPs    = 127.0.0.1
# 512 MB
httpServerMaxRequestBodySize = 536870912

[hashing]
function=sha256
# 64 chars, quoted. Example: "my_64_len_key_here..."
# e.g. tr -dc 'A-Za-z0-9!@#$%^&*()_+-=,./?;:' </dev/urandom | head -c 64
key=

[pim]
# the address of your UID Mapper component instance
uidMapAddr = https://your.uidmap.instance
pimTimeout = 1m5m
